site_name: Emlid
theme: docstheme
site_favicon: favicon.ico
repo_url: https://github.com/emlid/Docs
pages:
- Reach: index.md
- Introduction: introduction.md
- Roadmap: roadmap.md
- Kit contents: kit-contents.md
- Quickstart: quickstart.md
- Power supply: power-supply.md
- Antenna placement: antenna-placement.md
- ReachView app: reachview-app.md
- Hardware integration: hardware-integration.md
- PylonGPS: pylongps.md
- Firmware reflashing: firmware-reflashing.md
- Electrical specs: electrical-specs.md
- Mechanical specs: mechanical-specs.md
- Software development: software-development.md
- Troubleshooting: troubleshooting.md
- FAQ: faq.md
