site_name: Emlid
theme: readthedocs
site_favicon: favicon.ico
repo_url: https://github.com/emlid/Docs
pages:
- Introduction: index.md
- Reach:
  - Introduction: Reach/introduction/introduction.md
  - Roadmap: Reach/roadmap/roadmap.md
  - Kit contents: Reach/kit-contents/kit-contents.md
  - Quickstart: Reach/quickstart/quickstart.md
  - Power supply: Reach/power-supply/power-supply.md
  - Antenna placement: Reach/antenna-placement/antenna-placement.md
  - ReachView app: Reach/reachview-app/reachview-app.md
  - Hardware integration: Reach/hardware-integration/hardware-integration.md
  - GPS post-processing: Reach/gps-post-processing/gps-post-processing.md
  - PylonGPS: Reach/pylongps/pylongps.md
  - Firmware reflashing: Reach/firmware-update/firmware-update.md
  - Electrical specs: Reach/electrical-specs/electrical-specs.md
  - Mechanical specs: Reach/mechanical-specs/mechanical-specs.md
  - Software development: Reach/software-development/software-development.md
  - Troubleshooting: Reach/troubleshooting/troubleshooting.md
  - FAQ: Reach/faq/faq.md
