site_name: Emlid
theme: docstheme
site_favicon: favicon.ico
repo_url: https://github.com/emlid/reach-docs
pages:
- Reach: index.md
- Introduction: introduction.md
- Roadmap: roadmap.md
- Kit contents: kit-contents.md
- Quickstart: quickstart.md
- Power supply: power-supply.md
- Antenna placement: antenna-placement.md
- ReachView app: reachview-app.md
- Setting up correction link: reachview-link.md
- RTK configuration: reachview-configuration.md
- Monitoring status: reachview-status.md
- Hardware integration: hardware-integration.md
- PylonGPS: pylon-gps.md
- Firmware reflashing: firmware-reflashing.md
- Electrical specs: electrical-specs.md
- Mechanical specs: mechanical-specs.md
- Software development: software-development.md
- Troubleshooting: troubleshooting.md
- FAQ: faq.md
- Changelogs: changelogs.md